language: python
compiler:
- python
before_install:
- openssl aes-256-cbc -K $encrypted_a27c77282a93_key -iv $encrypted_a27c77282a93_iv -in deploy_libgd_key.enc -out deploy_libgd_key -d
- chmod 600 deploy_libgd_key
- eval `ssh-agent -s`
- ssh-add deploy_libgd_key
- sudo apt-get update -yqq
- sudo apt-get install python-pip
- sudo pip install -r requirements.txt
script:
- make publish
- git remote remove origin
- git remote add origin git@github.com:libgd/libgd.github.io.git
- git fetch --all
- 
- ghp-import -n -r origin -b master -m "$(git log -1 --oneline)" output
- git push --force origin master
