language: python
compiler:
  - python

before_install:
  - sudo apt-get update -yqq
  - sudo apt-get install python-pip
  - sudo pip install ghp-import pelican cpp-coveralls

before_script:
  - umask 0077; openssl aes-256-cbc -K $encrypted_f26bf31613db_key -iv $encrypted_f26bf31613db_iv -in my_key.enc -out my_key -d
  - echo -e "Host github.com\n  IdentityFile my_key" > ~/.ssh/config
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts

script:
  - make publish

after_success:
  - git remote remove origin
  - git remote add origin git@github.com:libgd/libgd.github.io.git
  - git fetch --all
  - #echo "libgd.org" > output/CNAME
  - ghp-import -n -r origin -b master -m "$(git log -1 --oneline)" output
  - git push --force origin master
